# Generated by Django 4.1 on 2023-08-14 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="create_date",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 23, 43, 42, 505775, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 23, 43, 42, 503775, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
