# Generated by Django 4.1 on 2023-08-14 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_comment_create_date_comment_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="create_date",
        ),
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 23, 44, 40, 933157, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 23, 44, 40, 935156, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
